{
  "LBL_AboutMe": "About Me",
  "LBL_AccessManagement": "Access Management",
  "LBL_Add": "Add",
  "LBL_AddPOI": "Add POI",
  "LBL_AddToRepository": "Add To Repository",
  "LBL_Address": "Address",
  "MSG_S_AllMarkersDeletedSuccessfully": "All Markers deleted successfully",
  "LBL_AllRecords": "All Records",
  "LBL_AllTabs": "All Tabs",
  "MSG_E_AnErrorOccurred": "An error occurred.",
  "LBL_Analysis": "Analysis",
  "MSG_E_AnalysisNotSupported": "Analysis not supported",
  "LBL_And": "And",
  "LBL_Applied": "Applied",
  "LBL_Apply": "Apply",
  "LBL_ApplyAll": "Apply All",
  "LBL_ApplyLabels": "Apply Labels",
  "LBL_ApplySelected": "Apply Selected",
  "LBL_BaseAudience": "Base Audience",
  "LBL_Bicycle": "Bicycle",
  "LBL_Blueprint": "Blueprint",
  "LBL_Calculate": "Calculate",
  "LBL_CalculateDistance": "Calculate Distance",
  "LBL_CalculateDuplicates": "Calculate Duplicates",
  "MSG_E_CampaignAlreadySelected": "Campaign already selected",
  "LBL_Category": "Category",
  "LBL_CentreMapHere": "Centre Map Here",
  "LBL_Clear": "Clear",
  "LBL_ClearAll": "Clear All",
  "LBL_ClearDirections": "Clear directions",
  "LBL_ClearLabels": "Clear Labels",
  "LBL_ClearSelection": "Clear Selection",
  "LBL_Close": "Close",
  "LBL_Continue": "Continue",
  "LBL_Conurbation": "Conurbation",
  "LBL_ConvertMapsToCampaign": "Convert Maps to Campaign",
  "LBL_CreateDefinition": "Create Definition",
  "MSG_I_CurrentSelectionIsReturningMoreThan70000Frames": "Current selection is returning more than 70,000 frames. Please apply further filters to reduce the result to 70,000 frames.",
  "LBL_CurrentTab": "Current Tab",
  "LBL_CustomMarkerIcon": "Custom Marker Icon",
  "LBL_CustomUpload": "Custom Upload",
  "LBL_DeleteShape": "Delete Shape",
  "LBL_DensityHeatmap": "Density Heatmap",
  "MSG_E_DensityHeatmapCanBeAppliedToFramesAndPoisOnly": "Density heatmap can be applied to Frames/POIs only",
  "LBL_DimensionCode": "Dimension Code",
  "LBL_DirectionsFromHere": "Directions From Here",
  "LBL_DirectionsToHere": "Directions To Here",
  "LBL_DrawingControls": "Drawing Controls",
  "LBL_Driving": "Driving",
  "LBL_Easting": "Easting",
  "MSG_W_EmailAddressHasAlreadyBeenAdded": "Email Address has already been added",
  "LBL_EnterMapTitle": "Enter Map Title",
  "LBL_Environment": "Environment",
  "MSG_E_ErrorWhileCreating": "Error while creating.",
  "MSG_E_ErrorWhileLoadingPois": "Error while loading POIs!",
  "MSG_E_ErrorWhileLoadingPostalSectorShapes": "Error while loading Postal Sector Shapes!",
  "MSG_E_ErrorWhileSavingTheMap": "Error while saving the map.",
  "LBL_ExportToExcel": "Export To Excel",
  "LBL_FillColour": "Fill Colour",
  "LBL_FillOpacity": "Fill Opacity",
  "LBL_FilterFrames": "Filter Frames",
  "LBL_FilterMarkers": "Filter Markers",
  "LBL_FilterPois": "Filter POIs",
  "LBL_FormatGroup": "Format Group",
  "LBL_FormatGroupColour": "Format Group Colour",
  "LBL_FormatType": "Format Type",
  "LBL_Frame": "Frame",
  "LBL_FrameCategories": "Frame Categories",
  "LBL_FrameCount": "Frame Count",
  "LBL_FrameLabel": "Frame Label",
  "LBL_FrameUniverse": "Frame Universe",
  "LBL_Frames": "Frames",
  "MSG_S_FramesAddedSuccessfully": "frames added successfully",
  "MSG_E_FramesToFramesAnalysisNotSupported_PleaseSelectDifferentTabs": "Frames to Frames analysis not supported. Please select different tabs",
  "LBL_FromFile": "From File",
  "LBL_General": "General",
  "MSG_E_GeocodeWasNotSuccessfulForTheFollowingReason": "Geocode was not successful for the following reason:",
  "LBL_GetDirections": "Get directions",
  "LBL_GetFrameCount": "Get Frame Count",
  "LBL_GetFrames": "Get Frames",
  "LBL_GetFrames_AllShapeTabs": "Get Frames (All Shape tabs)",
  "LBL_GetFrames_CurrentShape": "Get Frames (Current Shape)",
  "LBL_GetFrames_SelectedShapeTab": "Get Frames (Selected Shape tab)",
  "LBL_GetFrames_SelectedShapes": "Get Frames (Selected Shapes)",
  "LBL_GetStraightDistance": "Get Straight distance",
  "LBL_GettingFramesFor": "Getting frames for",
  "LBL_GettingFramesForXShape": "Getting frames for x shape",
  "LBL_GettingFramesForXShapes": "Getting frames for x shape(s)",
  "LBL_HeatMapGenerated": "Heat map generated",
  "LBL_Heatmap": "Heatmap",
  "MSG_S_HeatmapAddedSuccessfully": "Heatmap added successfully",
  "LBL_Heatmaps": "Heatmaps",
  "LBL_HideMarkers": "Hide Markers",
  "LBL_HoldingGroup": "Holding Group",
  "LBL_IndexAgainstSelectedGeography": "Index Against Selected Geography",
  "LBL_IndexAgainstUkAudience": "Index Against UK Audience",
  "LBL_IsSelected": "Is Selected",
  "LBL_Km": "KM",
  "LBL_Kms": "Kms",
  "LBL_Lattitude": "Lattitude",
  "LBL_Layers": "Layers",
  "LBL_LoadingFramesTab": "Loading  Frames Tab",
  "LBL_LoadingPoisTab": "Loading  Pois Tab",
  "LBL_LoadingShapesTab": "Loading  Shapes Tab",
  "LBL_Longitude": "Longitude",
  "MSG_E_MapCannotBeSaved_NoDataToSave": "Map cannot be saved. No data to save",
  "MSG_I_MapSaved": "Map saved",
  "MSG_S_MarkersAddedSuccessfully": "Markers added successfully",
  "LBL_MarketFrames": "Market Frames",
  "LBL_Max": "Max",
  "LBL_MediaOwner": "Media Owner",
  "LBL_Metadata": "Metadata",
  "LBL_Miles": "Miles",
  "LBL_Min": "Min",
  "MSG_E_MinDistanceCannotBeGreaterThanOrEqualToMaxDistance": "Min Distance cannot be greater than or equal to Max Distance.",
  "LBL_ModeOfTravel": "Mode Of Travel",
  "LBL_Name": "Name",
  "LBL_New": "New",
  "LBL_NewMap": "New Map",
  "MSG_E_NoFrameSelected": "No Frame(s) selected",
  "MSG_I_NoFramesAddedOrFramesAlreadyExists": "No frames added or frames already exists",
  "MSG_I_NoFramesFoundForAppliedFilters": "No frames found for applied filters",
  "MSG_I_NoFramesFoundForSelectedShapes": "No frames found for selected shape(s)",
  "MSG_I_NoFramesPresent": "No frames present",
  "MSG_E_NoFramesSelected": "No frames selected",
  "MSG_I_NoMapsAvailable": "No maps available",
  "MSG_E_NoMarkersPresentOnTheMap": "No markers present on the map",
  "MSG_E_NoMarkersSelected_PleaseSelectTheMarkersFirst": "No markers selected. Please select the markers first",
  "MSG_E_NoPOIsSelected": "No POI(s) selected",
  "MSG_E_NoShapesSelected": "No Shape(s) selected",
  "LBL_Northing": "Northing",
  "LBL_Open": "Open",
  "LBL_OpenMaps": "Open Maps",
  "LBL_OpeningMap": "Opening map:",
  "LBL_Package": "Package",
  "MSG_E_PleaseEnterPoiDefintionName": "Please enter poi defintion name.",
  "MSG_E_PleaseSelectATable": "Please select a table",
  "MSG_E_PleaseSelectAValidCampaign": "Please select a valid campaign",
  "MSG_E_PleaseSelectAValidEmailAddress": "Please select a valid Email Address",
  "MSG_E_PleaseSelectAValidMap": "Please select a valid map",
  "MSG_E_PleaseSelectAValidUser": "Please select a valid user",
  "MSG_E_PleaseSelectAccessRightFirst": "Please select access right first",
  "MSG_E_PleaseSelectFrameId": "Please select Frame Id.",
  "MSG_E_PleaseSelectFramesOrPOIsTab": "Please select Frames or POIs Tab",
  "MSG_E_PleaseSelectPlan": "Please select plan",
  "MSG_E_PleaseSelectPoiTabFirst": "Please select poi tab first",
  "MSG_E_PleaseSelectSourceAndDestination": "Please select source and destination",
  "MSG_E_PleaseSelectSourceAndTargetTabs": "Please select source and target tabs",
  "MSG_E_PleaseSelectTheFramesFirst": "Please select the frames first",
  "MSG_E_PleaseSelectTheMarkersLessThan": "Please select the markers less than",
  "MSG_E_PleaseSelectThePoiMarkers": "Please select the POI markers.",
  "MSG_E_PleaseSelectThePoisTab": "Please select the POIs tab.",
  "MSG_E_PleaseSelectThePostCodeField": "Please select the post code field",
  "MSG_E_PleaseSelectTheShapeTab": "Please select the shape tab",
  "MSG_E_PleaseSelectTheShapeToDelete": "Please select the shape to delete!",
  "MSG_E_PleaseSelectTheShapesFirst": "Please select the shapes first",
  "MSG_E_PleaseSelectTheShapesTab": "Please select the Shapes tab.",
  "MSG_E_PleaseSelectTheValidDistance": "Please select the valid distance.",
  "MSG_E_PleaseSelectValidInputs_SourceTabTargetTabCount": "Please select valid inputs (Source Tab/Target Tab/Count)",
  "MSG_E_PleaseSelectValidSourceAndDestination_YouCanCanculateDistanceBetweenOnly2FlaggedMarkers": "Please select valid source and destination. You can canculate distance between only 2 flagged markers.",
  "LBL_POI": "POI",
  "MSG_S_PoiAddedSuccessfully": "Poi added successfully",
  "MSG_S_PoiDefinitionCreated": "POI definition created",
  "LBL_PoiFrameColour": "POI Frame Colour",
  "LBL_PoiIdentity": "POI Identity",
  "LBL_PoiLabel": "POI Label",
  "LBL_PoiName": "POI Name",
  "LBL_PoiRadius": "POI Radius",
  "LBL_PoiType": "POI Type",
  "MSG_E_PoiTypeNeedToBeDefined": "Poi Type need to be defined",
  "MSG_S_PoisSaved": "Poi's Saved",
  "LBL_PostCode": "Post Code",
  "LBL_PostalCode": "Postal Code",
  "LBL_PostalSector": "Postal Sector",
  "LBL_Processing": "Processing",
  "LBL_Recieved": "recieved : ",
  "LBL_Repository": "Repository",
  "MSG_E_RepositoryNameMustBePresent": "Repository name must be present!",
  "LBL_RetailGroup": "Retail Group",
  "LBL_RetailGroupName": "Retail Group Name",
  "LBL_Save": "Save",
  "LBL_SaveMap": "Save Map",
  "LBL_SavedMap": "Saved Map",
  "MSG_I_SavingMap": "Saving map",
  "LBL_Segment": "Segment",
  "LBL_Select": "Select",
  "LBL_SelectACampaign": "Select a Campaign",
  "LBL_SelectAMapName": "Select a Map name",
  "LBL_SelectAProject": "Select a Project",
  "LBL_SelectAll": "Select All",
  "LBL_SelectMarket": "Select Market",
  "LBL_SelectPoisOrFramesTab": "Select POIs or Frames tab",
  "LBL_SelectSourceTab": "Select Source Tab",
  "LBL_SelectTargetTab": "Select Target Tab",
  "LBL_SelectedRecords": "Selected Records",
  "LBL_SelectedTabIsEmpty": "Selected tab is empty.",
  "LBL_Settings": "Settings",
  "LBL_Shape": "Shape",
  "LBL_ShapeFileName": "Shape File Name",
  "LBL_ShapeFiles": "Shape Files",
  "LBL_ShapeName": "Shape Name",
  "LBL_ShapeType": "Shape Type",
  "LBL_Shape_s": "shape(s)",
  "LBL_Shapeid": "ShapeId",
  "LBL_Shapes": "Shapes",
  "MSG_S_ShapesAddedSuccessfully": "Shapes added successfully",
  "MSG_E_ShapesToFramesAnalysisNotSupported_PleaseSelectDifferentTabs": "Shapes to Frames analysis not supported. Please select different tabs",
  "MSG_E_ShapesToPoisAnalysisNotSupported_PleaseSelectDifferentTabs": "Shapes to Pois analysis not supported. Please select different tabs",
  "LBL_ShareMap": "Share Map",
  "MSG_S_SharedSuccessfully": "shared successfully",
  "MSG_I_SharingMap": "Sharing Map",
  "LBL_Show": "Show",
  "LBL_ShowHide": "Show Hide",
  "LBL_ShowLabel": "Show Label",
  "LBL_ShowLegend": "Show Legend",
  "LBL_ShowMarkers": "Show Markers",
  "LBL_ShowTheRelationshipBetween": "Show The Relationship Between",
  "MSG_E_Sorry_TheMapWasUnableToObtainDirections_TheRequestFailedWithTheMessage": "Sorry",
  "LBL_Straight": "Straight",
  "LBL_StreetView": "Street View",
  "LBL_StrokeColour": "Stroke Colour",
  "LBL_StrokeOpacity": "Stroke Opacity",
  "LBL_StrokeWeight": "Stroke Weight",
  "MSG_E_TabNameCantBeBlank": "Tab name can't be blank",
  "LBL_TargetAudience": "Target Audience",
  "LBL_Title": "Title",
  "LBL_Total": "total :",
  "MSG_S_TotalRecordsFound_X": "Total records found : x",
  "LBL_Town": "Town",
  "LBL_Traffic": "Traffic",
  "LBL_Transit": "Transit",
  "LBL_TvArea": "TV Area",
  "LBL_Type": "Type",
  "MSG_E_UserAlreadySelected": "User already selected",
  "LBL_Walking": "Walking",
  "MSG_S_XFramesAddedSuccessfully": "%{count} frames added successfully",
  "MSG_S_XPoisAddedSuccessfully": "%{count} pois added successfully",
  "MSG_S_XShapesAddedSuccessfully": "%{count} shapes added successfully",
  "MSG_I_YouHaventSelectedAnyRecordsYet_PleaseSelectTheRows": "You haven't selected any records yet. Please select the rows.",
  "MSG_I_YouHaventSelectedAnyShapesYet_PleaseDrawOrSelectTheShapesToFilterFrames": "You haven't selected any shape(s) yet. Please draw/select the shape(s) to filter Frames.",
  "MSG_I_YouHaventSelectedAnyShapesYet_PleaseDrawOrSelectTheShapesToFilterPois": "You haven't selected any shape(s) yet. Please draw/select the shape(s) to filter Pois.",
  "LBL_ZoomIn": "Zoom In",
  "LBL_ZoomOut": "Zoom Out"
}